### ISSUE TITLE
[Story] Automation of releases creation

### ISSUE THREAD

**Issue by ouphi** [Azure/iotedge-lorawan-starterkit#1928]
## Description

Currently, the releases need to be created manually by a user. Most of the steps for creating a release can be automated in a pipeline instead of being done manually. 

The goal of this story is to automate some of the release steps in a pipeline:
- Build and push ARM32v7 and AMD64 images for Packet Forwarder and Network Server
- Package Azure Function
-  Package the Discovery Service
- Create New Release on GitHub
- Generate ARM file from Bicep
- Compile the provisioning CLI

Stretch goal: 
- The release creates a PR to update the default bicep version (templateBicep/main.bicep#40)
- The release creates a PR to update the docs (button) to point to the new version (quickstart.md#49)

## Acceptance criteria
- [x] A user can trigger a release creation from the Github UI.
  - [x] the user can specify the release tag

## Tasks
- [x] Build and push ARM32v7 and AMD64 images for Packet Forwarder and Network Server in pipeline
- [x] Package Azure Function in pipeline
- [x]  Package the Discovery Service in pipeline
- [x] Create New Release on GitHub in pipeline
- [x] Generate ARM file from Bicep
- [x] Compile the provisioning CLI

Stretch goal:
- [x] Update the update the URL button version and create a PR
- [ ] Update the bicep version and create a PR
