### ISSUE TITLE
[Story] Testing of release workflow steps on PR creation

### ISSUE THREAD

**Issue by ouphi** [Azure/iotedge-lorawan-starterkit#1943]
## Description

The release workflow will not be running often, it only run if a user triggers manually.
There is a risk that this workflow gets broken without us knowing it. For example, if somebody adds a mandatory arg to the basic station Dockerfile, the job building the image would be broken, but we would only notice it when creating a release.

A solution could be:
- Trigger the release workflow on PR
- Disable steps that we only want to happen on a real release. For example pushing images and the release creation would be disabled when the trigger is `pull_request`.

## Acceptance criteria

- [ ] The risk to break the release workflow is minimised
- [ ] Most of the release workflow is tested on PR.

## Tasks
- [ ] Add a pull_request trigger
- [ ] Disable release creation if the trigger is not `workflow_dispatch`
- [ ] Disable publishing images to docker hub if the trigger is not `workflow_dispatch`
