### ISSUE TITLE
[Story] Create pull requests from release workflow

### ISSUE THREAD

**Issue by ouphi** [Azure/iotedge-lorawan-starterkit#1950]
## Description

Add the following functionality to the prerelease workflow:
- Create a PR updating the URL button version in the doc (quickstart.md#49), on the target branch `docs/main`.
- Create a PR updating the default bicep version (templateBicep/main.bicep#40), on the target branch `dev`

This is a follow up of this [story](https://github.com/Azure/iotedge-lorawan-starterkit/issues/1928).

## Acceptance criteria

- [x] When a release is triggered, 2 pull requests are created:
  - [x] One pull request to update the version in bicep
  - [x] One pull request to update the version of the button URL in the doc 

## Tasks
- [x] Create a custom action to create pull requests
- [x] Update the bicep file & use the custom action to create a PR in workflow
- [x] Update the button URL & use the custom action to create a PR in workflow
